services:
    Redeye\GraphqlFederationBundle\Command\DumpFederatedSchemaCommand:
        arguments:
            $requestExecutor: @overblog_graphql.request_executor
        tags:
            - { name: 'console.command', command: "redeye:graphql:dump-federated" }

    Redeye\GraphqlFederationBundle\Schema\FederatedSchemaBuilder:
        arguments:
            $typeResolver: '@Overblog\GraphQLBundle\Resolver\TypeResolver'
